from enum import Enum

class ControlState(str, Enum):
    REQUEST_INITIATED = "REQUEST_INITIATED"
    PROFILE_RETRIEVED = "PROFILE_RETRIEVED"
    KEYWORD_FILTER_CHECK = "KEYWORD_FILTER_CHECK"
    CACHE_CHECK = "CACHE_CHECK"
    AI_ANALYSIS = "AI_ANALYSIS"
    ACCESS_DECIDED = "ACCESS_DECIDED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"